vich_uploader:
    db_driver: orm

    mappings:
        imageBeforeFile:
            uri_prefix: /images/imageBeforeFile
            upload_destination: '%kernel.project_dir%/public/images/imageBeforeFile'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
            delete_on_update: true

        imageAfterFile:
            uri_prefix: /images/imageAfterFile
            upload_destination: '%kernel.project_dir%/public/images/imageAfterFile'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
            delete_on_update: true

        logoFiles:
            uri_prefix: /images/logoFiles
            upload_destination: '%kernel.project_dir%/public/images/logoFiles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
            delete_on_update: true